### ISSUE TITLE
External Emotes do not work in embeds in WFP discord, but you can circumvent it. 

### ISSUE THREAD

**Issue by snowclipsed** [KQM-git/keqing-lite-interactions#218]
<h3>
Issue : External Emotes will not work for Kikin in WFP.
</h3>

External Emojis do not work for Kikin in WFP for any embed. Commands like /character do not show emotes like : 

![image](https://user-images.githubusercontent.com/66517217/230432685-7e7c15c9-b069-46c2-bfd3-c539e2df8c9b.png)

<h3>
Fix (only for /characters):
</h3>
We encountered the same problem for hikin (the kikin fork for WFP guides).

![image](https://user-images.githubusercontent.com/66517217/230442754-4d9296ec-55c0-43b4-89db-b41da3cc91f3.png)

Which is present for all bots in WFP:

![image](https://user-images.githubusercontent.com/66517217/230443944-5870ebcb-befe-489d-b0d2-ebb0d24343a1.png)

The fix was relatively easy - Instead of description, use `author` field. With `author` element emotes in /character can be supported as icon_url. The image links can be accessed from [KQM Portrait Cards](https://library.keqingmains.com/resources/tools/portraits) for each element. 

<h3> Example : </h3>

<h4> Instead of this : </h4>

```yaml
embeds:
  - color: ${COLORS.ANEMO_GREEN}
    description: |-
      <${EMOJIS.ELEMENT_ANEMO}> Select a character!
```

<h4> Use : </h4>

```yaml
embeds:
  - color: ${COLORS.ANEMO_GREEN}
    author:
      name: Select a character!
      icon_url: https://library.keqingmains.com/img/elements/anemo.png
```

Which should fix the emote problem. 

![image](https://user-images.githubusercontent.com/66517217/230444022-fd4adbca-ed48-4c65-93a3-6ef99ea56150.png)
